name = "my name sandro"
#name aris cvladi
# = aric cvladistvis mnisvnelobis mimnisebeli
# "sandro" aris cvladistvis mnisvnelovani

surname = "chapidze I am" 

# print(name)
#orint punqcia gadaecema ekranze gamosatani obieqti

name = "my name sandro" # es aris (string) tipis cvladi
age =   14  # es aris int(integer) mteli ricxvi
height =   1.51 #es aris float tipis cvladi( atwiladi)
#boolean (bool) tipis cvladi

know_programming = True  # True an Folse
is_ugly = False  #sneccose(ubralod weris stili)

isugle = False # javaskriptuli comelclase


print(name +" "+ surname +" "+ str(age) +" "+ str(height)) 


#stringi aris brwyalebci moqceuli simboloebi









#print(tipe(age))
#print(tipe(name))
#print(tipe(surname))
#print(tipe(height))
#print(tipe(knows_programming))











