from turtle import *

#we wont to paint a house

#step 1:  drow a square
speed(30)

width(7)
color("blue")

forward(400)
left(90)

forward(250)
left(90)

forward(400)
left(90)

forward(250)
left(90)
#end of square

#drawing a door

forward(100)
color("yellow")
begin_fill()
left(90)
forward(130)    #height of the door
right(90)
forward(90)
right(90)
forward(130)
end_fill()
penup()
goto(400, 250)
pendown()

color("red")
begin_fill()
left(235)
forward(245)
left(70)
forward(245)
end_fill()

color("blue")
left(55)
forward(252)

left(90)
forward(100)
left(90)
color("yellow")
forward(70)
left(90)
color("black")
left(180)
forward(10)
left(180)
forward(15)
left(90)
color("yellow")
forward(70)
color("blue")
left(90)
forward(150)
left(90)
color("white")
forward(100)
color("black")
color("brown")
begin_fill()
forward(100)
left(90)
left(180)

forward(100)
left(90)
left(180)

forward(100)
left(180)
left(90)

forward(100)
left(90)
forward(5)
end_fill()
color("white")
forward(100)
color("blue")
left(90)
forward(10)
color("black")
left(90)     
left(180)
        
color ("white")
        
forward(100)
color("green")
left(90)
        
width(200)
        
forward(300)   
color("black")
left(90)
left(180)

color("green")
forward(180)
left(90)
left(180)
forward(300)
width(550)
forward(700)
color("black")

left(90)
left(180)
width(7)

color("green")
forward(200)
color("black")
width(30)
forward(250)
color("green")
width(200)

forward(20)

color("black")



left(90)
left(180)
width(7)
color("green")
forward(200)
width(200)
forward(50)
width(30)
left(90)
left(180)
forward(100)
color("black")
forward(160)

forward(50)
color("green")

left(90)

color("green")

forward(800)
left(90)

forward(100)

color("white")



forward(325)

left(180)
left(90)
left(40)
color("yellow")
width(150)
forward(10)
color("black")

color("yellow")

exitonclick()